/* RC_RuijieClient.c generated by valac, the Vala compiler
 * generated from RC_RuijieClient.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <dbus/dbus-glib.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <dbus/dbus.h>

#define _dbus_g_connection_unref0(var) ((var == NULL) ? NULL : (var = (dbus_g_connection_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_RUIJIE_DBUS_SERVER (ruijie_dbus_server_get_type ())
#define RUIJIE_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RUIJIE_DBUS_SERVER, RuijieDbusServer))
#define RUIJIE_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RUIJIE_DBUS_SERVER, RuijieDbusServerClass))
#define IS_RUIJIE_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RUIJIE_DBUS_SERVER))
#define IS_RUIJIE_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RUIJIE_DBUS_SERVER))
#define RUIJIE_DBUS_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RUIJIE_DBUS_SERVER, RuijieDbusServerClass))

typedef struct _RuijieDbusServer RuijieDbusServer;
typedef struct _RuijieDbusServerClass RuijieDbusServerClass;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _DBusObjectVTable _DBusObjectVTable;

struct _DBusObjectVTable {
	void (*register_object) (DBusConnection*, const char*, void*);
};



static guint _dynamic_request_name0 (DBusGProxy* self, const char* param1, guint param2, GError** error);
RuijieDbusServer* ruijie_dbus_server_new (void);
RuijieDbusServer* ruijie_dbus_server_construct (GType object_type);
GType ruijie_dbus_server_get_type (void);
static inline void _dynamic_set_State0 (DBusGProxy* obj, gint value);
static inline gint _dynamic_get_State1 (DBusGProxy* obj);
void _main (void);
static void _vala_dbus_register_object (DBusConnection* connection, const char* path, void* object);
static void _vala_dbus_unregister_object (gpointer connection, GObject* object);



static guint _dynamic_request_name0 (DBusGProxy* self, const char* param1, guint param2, GError** error) {
	guint result;
	dbus_g_proxy_call (self, "RequestName", error, G_TYPE_STRING, param1, G_TYPE_UINT, param2, G_TYPE_INVALID, G_TYPE_UINT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0U;
	}
	return result;
}


static inline void _dynamic_set_State0 (DBusGProxy* obj, gint value) {
	DBusGProxy* property_proxy;
	GValue gvalue = {0};
	property_proxy = dbus_g_proxy_new_from_proxy (obj, DBUS_INTERFACE_PROPERTIES, NULL);
	g_value_init (&gvalue, G_TYPE_INT);
	g_value_set_int (&gvalue, value);
	dbus_g_proxy_call (property_proxy, "Set", NULL, G_TYPE_STRING, dbus_g_proxy_get_interface (obj), G_TYPE_STRING, "State", G_TYPE_VALUE, &gvalue, G_TYPE_INVALID, G_TYPE_INVALID);
	g_object_unref (property_proxy);
}


static inline gint _dynamic_get_State1 (DBusGProxy* obj) {
	DBusGProxy* property_proxy;
	GValue gvalue = {0};
	gint result;
	property_proxy = dbus_g_proxy_new_from_proxy (obj, DBUS_INTERFACE_PROPERTIES, NULL);
	dbus_g_proxy_call (property_proxy, "Get", NULL, G_TYPE_STRING, dbus_g_proxy_get_interface (obj), G_TYPE_STRING, "State", G_TYPE_INVALID, G_TYPE_VALUE, &gvalue, G_TYPE_INVALID);
	g_object_unref (property_proxy);
	result = g_value_get_int (&gvalue);
	return result;
}


void _main (void) {
	GError * _inner_error_;
	GMainLoop* loop;
	_inner_error_ = NULL;
	loop = g_main_loop_new (NULL, FALSE);
	{
		DBusGConnection* conn;
		DBusGProxy* bus;
		guint request_name_result;
		conn = dbus_g_bus_get (DBUS_BUS_SESSION, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
			goto __finally0;
		}
		bus = dbus_g_proxy_new_for_name (conn, "org.freedesktop.DBus", "/org/freedesktop/DBus", "org.freedesktop.DBus");
		request_name_result = _dynamic_request_name0 (bus, "com.googlecode.ruijieclient", (guint) 0, &_inner_error_);
		if (_inner_error_ != NULL) {
			_dbus_g_connection_unref0 (conn);
			_g_object_unref0 (bus);
			goto __catch0_g_error;
			goto __finally0;
		}
		if (request_name_result == DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER) {
			RuijieDbusServer* server;
			server = ruijie_dbus_server_new ();
			_vala_dbus_register_object (dbus_g_connection_get_connection (conn), "/com/googlecode/ruijieclient", (GObject*) server);
			_g_object_unref0 (server);
		} else {
			DBusGProxy* test;
			test = dbus_g_proxy_new_for_name (conn, "com.googlecode.ruijieclient", "/com/googlecode/ruijieclient", "com.googlecode.ruijieclient");
			_dynamic_set_State0 (test, 7);
			g_message ("RC_RuijieClient.vala:25: %d", _dynamic_get_State1 (test));
			_g_object_unref0 (test);
			_dbus_g_connection_unref0 (conn);
			_g_object_unref0 (bus);
			_g_main_loop_unref0 (loop);
			return;
		}
		_dbus_g_connection_unref0 (conn);
		_g_object_unref0 (bus);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "error: %s\n", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_main_loop_unref0 (loop);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	g_main_loop_run (loop);
	_g_main_loop_unref0 (loop);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_main ();
	return 0;
}


static void _vala_dbus_register_object (DBusConnection* connection, const char* path, void* object) {
	const _DBusObjectVTable * vtable;
	vtable = g_type_get_qdata (G_TYPE_FROM_INSTANCE (object), g_quark_from_static_string ("DBusObjectVTable"));
	if (vtable) {
		vtable->register_object (connection, path, object);
	} else {
		g_warning ("Object does not implement any D-Bus interface");
	}
}


static void _vala_dbus_unregister_object (gpointer connection, GObject* object) {
	char* path;
	path = g_object_steal_data ((GObject*) object, "dbus_object_path");
	dbus_connection_unregister_object_path (connection, path);
	g_free (path);
}




